version: "3.9"
services:
  app:
  # run `docker build -t my-rails-app .` to build the image
    image: my-rails-app-vol
    environment:
      DB_NAME: d21
      DB_USER: root
      DB_PASSWD: password
      DB_HOST: host.docker.internal
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: 
      - /bin/sh
      - -c
      - |
        yarn
        yarn res:dev
        foreman start -f Procfile.dev
  # I'm not using another container for the DB so commenting this 
  # db:
    # image: postgres:alpine3.15
    # environment:
      # POSTGRES_PASSWORD: example